name: branch_links
description: A new Flutter project.
homepage: https://github.com/mgmri-dge/branch_sop
publish_to: https://mgmresorts.jfrog.io/artifactory/api/pub/dge-pub
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.5
  collection: ^1.18.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_web_plugins:
    sdk: flutter
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.8.1
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.15.0
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  sentry_flutter: ^8.14.0
  sentry_logging: ^8.14.0
  string_validator: ^1.1.0
  url_launcher: ^6.3.1

  vega_components:
    hosted: https://mgmresorts.jfrog.io/artifactory/api/pub/dge-pub
    version: ^3.1.0
  vega_tokens:
    hosted: https://mgmresorts.jfrog.io/artifactory/api/pub/dge-pub
    version: ^1.4.0
  

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.2
  fake_cloud_firestore: ^3.1.0
  firebase_database_mocks: ^0.7.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.6.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  fonts:
    - family: Calibre-R
      fonts:
        - asset: assets/fonts/Calibre-R-Regular.otf
        - asset: assets/fonts/Calibre-R-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Calibre-R-Medium.otf
          weight: 500
        - asset: assets/fonts/Calibre-R-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Calibre-R-Bold.otf
          weight: 700
        - asset: assets/fonts/Calibre-R-BoldItalic.otf
          weight: 700
          style: italic
  assets:
    - assets/icons/
    - assets/images/
