name: inline_markdown_files
description: 'Process markdown to inline information from files to enhance documentation'
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.5.0
  glob: ^2.1.3
  path: ^1.9.1
  yaon: ^1.1.4+10

dev_dependencies:
  flutter_lints: ^5.0.0
