name: Dart Vulnerability Scan
description: Perform Google based Vulnerability Scan
inputs:
  lock-file:
    default: ''
    description: Path to the pubspec.lock file to validate.  Typically only required for monorepos.
    required: false
  path:
    default: .
    description: Path to the Dart / Flutter package to validate
    required: false
  token:
    description: GitHub Auth token for the repository
    required: true

runs:
  using: 'composite'
  steps:
    - name: Extract package name from "pubspec.yaml"
      id: extract_package_name
      shell: bash
      run: |
        set -e
        if test -f "${{ inputs.path }}/pubspec.yaml"; then
          package_name=$(grep -m 1 '^name:' "${{ inputs.path }}/pubspec.yaml" | cut -d ' ' -f 2)
          echo "PACKAGE_NAME=${package_name}" >> $GITHUB_ENV
        else
          echo "No pubspec.yaml file found in the specified path."
          exit 1
        fi

    - name: Echo Lock file (default)
      if: inputs.lock-file == ''
      shell: bash
      run: |
        echo "Using default lock file"

    - name: Echo Lock file (custom)
      if: inputs.lock-file != ''
      shell: bash
      run: |
        echo "Using custom lock file: ${{ inputs.lock-file }}"

    # Docs: https://google.github.io/osv-scanner/github-action/
    # Releases: https://github.com/google/osv-scanner-action/tags
    - name: 'Run scanner with Default lock file'
      uses: google/osv-scanner-action/osv-scanner-action@v2.0.0
      if: inputs.lock-file == ''
      with:
        scan-args: |-
          --output=${{ inputs.path }}/results.json
          --format=json
          -r
          --lockfile ${{ inputs.path }}/pubspec.lock
          ${{inputs.path}}
      continue-on-error: true
    - name: 'Run scanner with Custom lock file'
      uses: google/osv-scanner-action/osv-scanner-action@v2.0.0
      if: inputs.lock-file != ''
      with:
        scan-args: |-
          --output=${{ inputs.path }}/results.json
          --format=json
          -r
          --lockfile ${{ inputs.lock-file }}
          ${{inputs.path}}
      continue-on-error: true
    - name: 'Run osv-scanner-reporter'
      uses: google/osv-scanner-action/osv-reporter-action@v2.0.0
      with:
        scan-args: |-
          --output=${{ inputs.path }}/${{ env.PACKAGE_NAME }}.sarif
          --new=${{ inputs.path }}/results.json
          --fail-on-vuln=true
    - name: 'Delete Existing artifact, if exists'
      uses: geekyeggo/delete-artifact@v5
      with:
        failOnError: false
        name: ${{ env.PACKAGE_NAME }}.sarif
    - name: 'Upload artifact'
      id: 'upload_artifact'
      if: ${{ !cancelled()}}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}.sarif
        path: ${{ inputs.path }}/${{ env.PACKAGE_NAME }}.sarif
        retention-days: 5
    - name: 'Upload to code-scanning'
      if: ${{ !cancelled() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: security-${{ env.PACKAGE_NAME }}
        sarif_file: ${{ inputs.path }}/${{ env.PACKAGE_NAME }}.sarif
