name: auto_build_number
description: 'Dart based GitHub Action that can create build numbers'
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
