// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? currentPlatform({required bool isDev}) {
    if (kIsWeb) {
      if (isDev) {
        return webDev;
      } else {
        return web;
      }
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        // handled by GoogleService-Info.plist
        return null;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: "AIzaSyDsK3TRBxfwjQolj0gIfDP4kqGrQ1gukik",
    authDomain: "mgm-resorts-app.firebaseapp.com",
    databaseURL: "https://mgm-resorts-app.firebaseio.com",
    projectId: "mgm-resorts-app",
    storageBucket: "mgm-resorts-app.appspot.com",
    messagingSenderId: "680758060118",
    appId: "1:680758060118:web:1d0310ace553b9c4fdc7f7",
    measurementId: "G-TG3Q9N35MQ",
  );

  static const webDev = FirebaseOptions(
    apiKey: "AIzaSyCQ-Y9hG4qMvCs30BcscJZkYbLNe_dZLyk",
    authDomain: "mgm-resorts-dev.firebaseapp.com",
    databaseURL: "https://mgm-resorts-dev-default-rtdb.firebaseio.com",
    projectId: "mgm-resorts-dev",
    storageBucket: "mgm-resorts-dev.appspot.com",
    messagingSenderId: "272887929731",
    appId: "1:272887929731:web:389b1fcb60fda30be474b6",
    measurementId: "G-791JKDNRK6",
  );
}
