include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    always_use_package_imports: true

analyzer:
  errors:
    depend_on_referenced_packages: ignore
  exclude:
    - .fvm/**
    - '**/*.g.dart'
    - '**/*.gql.dart'
