name: 'Deploy to Live Channel - Reference Implementation'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - "lib/**"
    - "web/**"

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write
  pull-requests: write
  security-events: write 

env:
  jf_url: https://mgmresorts.jfrog.io/artifactory/api/pub/dge-pub
  jf_disable_job_summary: false
  oidc_provider_name: "test-exploration-oidc"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4

      - name: Parse Repo URL
        shell: bash
        run: |
            echo "JFROG_BASE_URL=https://`echo ${{ env.jf_url }} | awk -F/ '{print $3}'`" >> $GITHUB_ENV

      - name: Setup JFrog CLI
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
            JF_URL: ${{ env.JFROG_BASE_URL }}
            JFROG_CLI_RELEASES_REPO: ${{ env.jf_url }}
            JFROG_CLI_EXTRACTORS_REMOTE: ${{ env.jf_url }}
            JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            disable-job-summary: ${{ env.jf_disable_job_summary }}
            oidc-provider-name: ${{ env.oidc_provider_name }}
    
      - name: Set the JFrog Token
        shell: bash
        run: echo JFROG_TOKEN=${{ steps.setup-cli.outputs.oidc-token }} >> $GITHUB_ENV

      - name: Configure fvm
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
  
      - name: Set Pub URL
        shell: bash
        run: |
          set -e
          if test "${{ env.jf_url }}" != ""; then
            export PUB_HOSTED_URL=${{ env.jf_url }}
          fi
  
      - name: Add JFrog Token to Dart
        shell: bash
        run: |
          echo ${{ env.JFROG_TOKEN }} | dart pub token add ${{ env.jf_url }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Verify formatting
        run: |
          dart format --set-exit-if-changed test lib

      - name: Build dev web app
        run: flutter build web --release --dart-define=FLAVOR=dev

    #   - uses: FirebaseExtended/action-hosting-deploy@v0
    #     with:
    #       repoToken: "${{ secrets.GITHUB_TOKEN }}"
    #       firebaseServiceAccount: "${{ secrets.FIREBASE_DEV_SERVICE_ACCOUNT }}"
    #       projectId: mgm-resorts-dev
    #       channelId: live
    #       target: branchSOP

      - name: Build prod web app
        run: flutter build web --release --dart-define=FLAVOR=prod

      - name: Upload prod web build to JFrog
        run: |
          jf rt upload "build/web/**" "dge-pub/flutter-webapp/${{ github.sha }}/" \
            --flat=false \
            --build-name=flutter-webapp \
            --build-number=${{ github.run_number }}

    #   - uses: FirebaseExtended/action-hosting-deploy@v0
    #     with:
    #       repoToken: "${{ secrets.GITHUB_TOKEN }}"
    #       firebaseServiceAccount: "${{ secrets.FIREBASE_PROD_SERVICE_ACCOUNT }}"
    #       projectId: mgm-resorts-app
    #       channelId: live
    #       target: branchSOP